"""first migration

Revision ID: e873bde41999
Revises: 
Create Date: 2024-05-03 18:17:18.604614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e873bde41999'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('causa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idJuicio', sa.String(), nullable=False),
    sa.Column('estadoActual', sa.String(), nullable=True),
    sa.Column('idMateria', sa.Integer(), nullable=True),
    sa.Column('idProvincia', sa.String(), nullable=True),
    sa.Column('idCanton', sa.String(), nullable=True),
    sa.Column('idJudicatura', sa.String(), nullable=True),
    sa.Column('nombreDelito', sa.String(), nullable=True),
    sa.Column('fechaIngreso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idJuicio')
    )
    op.create_table('incidente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idIncidenteJudicatura', sa.Integer(), nullable=False),
    sa.Column('idMovimientoJuicioIncidente', sa.Integer(), nullable=False),
    sa.Column('fechaCrea', sa.DateTime(), nullable=True),
    sa.Column('incidente', sa.Integer(), nullable=True),
    sa.Column('causa_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['causa_id'], ['causa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actuacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('idJudicatura', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('actividad', sa.Text(), nullable=True),
    sa.Column('visible', sa.String(), nullable=True),
    sa.Column('origen', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('nombreArchivo', sa.String(), nullable=True),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('litigante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipoLitigante', sa.String(), nullable=True),
    sa.Column('nombresLitigante', sa.String(), nullable=True),
    sa.Column('representadoPor', sa.String(), nullable=True),
    sa.Column('incidente_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('litigante')
    op.drop_table('actuacion')
    op.drop_table('incidente')
    op.drop_table('causa')
    # ### end Alembic commands ###
